cabal-version:      2.4
name:               uruk
version:            0.1.0.0

synopsis:           A linear-non-linear graded programming language based on LNL-RMM.
description:        Uruk is an experimental implementation of LNL-RMM (the linear-non-linear
                    relative monadic metalanguage), a calculus combining linear types,
                    non-linear types, and first-class grade types for cost-sensitive
                    programming with effects.
license:            MIT
author:             Jack Liell-Cock
maintainer:         jackliellcock@gmail.com
copyright:          2026 Jack Liell-Cock

executable uruk
  main-is:          Main.hs
  default-language: Haskell2010
  hs-source-dirs:   src

  other-modules:
    Types
    Syntax
    Environment
    Eval
    Parsing.Token
    Parsing.Parser
    Parsing.Lexer
    Parsing.SugaredSyntax
    Parsing.Desugar
    Inference.Monad
    Inference.Infer
    Inference.Context
    Inference.Substitutable
    Inference.Unify
    Inference.Grades

  build-depends:
    base >= 4.16.4.0,
    containers >= 0.6.5.1,
    text >= 1.2.5.0,
    mtl >= 2.3.1,
    array >= 0.5

  build-tool-depends:
    alex:alex >= 3.2,
    happy:happy >= 1.20

test-suite uruk-test
  type:             exitcode-stdio-1.0
  main-is:          Main.hs
  default-language: Haskell2010
  hs-source-dirs:   test, src

  other-modules:
    Types
    Syntax
    Environment
    Eval
    Parsing.Token
    Parsing.Parser
    Parsing.Lexer
    Parsing.SugaredSyntax
    Parsing.Desugar
    Inference.Monad
    Inference.Infer
    Inference.Context
    Inference.Substitutable
    Inference.Unify
    Inference.Grades

  build-depends:
    base >= 4.16.4.0,
    containers >= 0.6.5.1,
    text >= 1.2.5.0,
    mtl >= 2.3.1,
    array >= 0.5,
    directory >= 1.3,
    filepath >= 1.4

  build-tool-depends:
    alex:alex >= 3.2,
    happy:happy >= 1.20
