-- | Grade-equation solver for Uruk.
--
-- This is the module that replaces Cambria's @Inference.Effects@: where
-- Cambria does effect-row inference, Uruk discharges grade equations
-- generated by the elaborator. For v0 the grade theory is fixed to
-- @(ℕ, +, 0)@ and the solver is simplification + zero-residual check.
--
-- v1 will turn this into a pluggable interface so that users can supply
-- their own grade theories (lattices, free SMCs with equations, etc.).
--
-- Real implementation lands in Milestone 3.
module Inference.Grades where

import Types (Grade)

-- | An equation between two grade expressions, collected by the elaborator.
data GradeEq = GradeEq Grade Grade
  deriving (Eq, Show)

-- | Solve a list of grade equations under the v0 @(ℕ, +, 0)@ theory.
-- Returns either an error message or a substitution discharging the
-- equations. Stub for Milestone 0.
solve :: [GradeEq] -> Either String ()
solve _ = Right ()
